config/routes.rb
Rails.application.routes.draw do

  if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" =>
      proc { [200, {}, [ ENV["ACME_KEY"] ] ] }
  else
    ENV.each do |var, _|
      next unless var.start_with?("ACME_TOKEN_")
      number = var.sub(/ACME_TOKEN_/, '')
      get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" =>
        proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
    end
  end
  
  resources :companies do
     collection do
       delete :destroy_all_listings
     end
  end

  resources :companies

  resources :admins
  resources :admin_sessions, only: [:new, :create, :destroy]

  resources :listings do
    get :autocomplete_company_name, :on => :collection
  end

  resources :listings

  resources :external_listings, only: [:new, :create, :index, :edit, :update, :destroy]

  get "login" => "admin_sessions#new"
  get "logout" => "admin_sessions#destroy"

  get "pages/home"
  get "pages/b_1619"
  get "pages/pass"
  get "pages/subsidy"
  get "pages/ticket_to_work"
  get "pages/trial_work_period"
  get "pages/sga"
  get "pages/benefits_calc"
  post "pages/benefits_calc"

  root to: "pages#home"

  get '*path' => redirect('/')
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :company

  def self.company_field_error_message
    "name entered doesn't exist. You must first" +
    " create a company with the" +
    " <a href='/companies/new'>New Company</a>" +
    " form before you can create listings for it. If you already created" +
    " the company, ensure correct spelling by typing in the name and" +
    " selecting it when it appears."
  end

  validates :company, presence: { allow_blank: false,
    message: Listing.company_field_error_message }
  include PgSearch
  pg_search_scope :search_listings, against: [
                                              :member_working,
                                              :job_title,
                                              :description,
                                              :working_hours_desc,
                                              :hours_weekly,
                                              :shift,
                                              :te_placement_manager
                                             ],
                  using: { tsearch: { dictionary: "english" } }
  pg_search_scope :search_listing_by_company, against: :company_id,
                  using: { tsearch: { dictionary: "english" } }

  def self.search(search)
    if search
      self.search_listings(search)
    else
      all
    end
  end

  def self.search_companies_and_listings(param)
    listings = Listing.search(param)
    company_listings = Company.search(param)
    listings.union(company_listings)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login,
    only: [:new, :create, :edit, :destroy, :update]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_referer, only: [:destroy, :edit, :new]
  before_action :normalize_create_update_params, only: [:update, :create]
  autocomplete :company, :name
  include ApplicationHelper

  attr_accessor :result, :listing
  helper_method :result, :listing

  def index
    @result = search_handler
    @result = filter_handler(@result)
    @result = paginated(@result)
  end

  def search_handler
    if params[:search].nil? || params[:search].empty?
      flash.now[:success] = "Displaying all listings"
      return Listing.all
    end

    result = Listing.search_companies_and_listings(params[:search])

    if result.empty?
      flash.now[:error] = "No jobs found with that search - Displaying all" +
        " listings"
      Listing.all
    else
      result
    end
  end

  def filter_handler(result)
    result = show_open_jobs(result) if params[:open_jobs]
    result = employment_filterer(result, params[:employment_filter]) if
      params[:employment_filter]
    if params[:order]
      result = orderer(result, params[:order], params[:order_direction])
    else
      result = orderer(result, "company_id")
    end
    result
  end

  def new
    @listing = Listing.new
  end

  def show
  end

  def edit
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to(session.delete(:return_to), notice:
        "Listing was successfully deleted.") }
      format.json { head :no_content }
    end
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.valid?
      @listing.update(listing_params)
      redirect_to(session.delete(:return_to), notice:
        "Listing edited successfully")
    else
      flash[:error] = @listing.errors.full_messages.to_sentence
      redirect_to(session.delete(:return_to))
    end
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.valid?
      @listing.save
      redirect_to(session.delete(:return_to), notice:
        "Listing created successfully")
    else
      flash[:error] = @listing.errors.full_messages.to_sentence
      redirect_to(session.delete(:return_to))
    end
  end

  rescue_from "ActiveRecord::InvalidForeignKey" do
    flash[:error] = Listing.company_field_error_message
    redirect_to(new_listing_path)
  end

  def employment_filterer(listings, filter)
    listings.where("employment_type = ?", filter)
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def normalize_create_update_params
      params[:listing][:wage] = decimal_to_int(params[:listing][:wage].to_s)
      params[:listing][:hours_weekly] = decimal_to_int(params[:listing]\
        [:hours_weekly].to_s)
      params[:listing][:member_working] = member_working_sanitizer(\
        params[:listing][:member_working])
    end

    def listing_params
      params.require(:listing).permit(:job_title, :company_id, :description,
        :wage, :working_hours_desc, :hours_weekly, :shift, :employment_type,
        :start_date, :est_end_date, :te_placement_manager, :member_working)
    end    
end

app/helpers/listings_helper.rb
module ListingsHelper
  def zero_wage_handler(wage)
    if wage.to_f == 0
      "N/A"
    else
      decimalize(wage)
    end
  end
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</p>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :company_name, "Company Name" %><br>
    <%= f.hidden_field :company_id, id: "my_company_id" %>
    <%= f.autocomplete_field :company, autocomplete_company_name_listings_path, 'data-auto-focus': true, id_element: "#my_company_id", class: "form-control",
      required: true %>
    <div class="instruction-text">Select the company as it appears while typing</div>
  </div>
  <div class="field form-group">
    <%= f.label :job_title, "Job Title" %><br>
    <%= f.text_field :job_title, class: "form-control", required: true %>
    <div class="instruction-text">e.g. Delivery driver</div>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
    <div class="instruction-text">e.g. Complete rush deliveries to attorneys</div>
  </div>
  <div class="field form-group">
    <%= f.label :wage %><br>
    <%= f.text_field :wage, class: "form-control",
      value: decimalize(listing.wage), required: true %>
    <div class="instruction-text">e.g. 15.00</div>
  </div>
  <div class="field form-group">
    <%= f.label :working_hours_desc, "Schedule" %><br>
    <%= f.text_field :working_hours_desc, class: "form-control" %>
    <div class="instruction-text">e.g. M-F 9am-5pm</div>
  </div>
  <div class="field form-group">
    <%= f.label :hours_weekly, "Hours/week" %><br>
    <%= f.text_field :hours_weekly, class: "form-control",
      value: decimalize(listing.hours_weekly), required: true %>
    <div class="instruction-text">e.g. 40.00</div>
  </div>
  <div class="form-group" id="select">
    <%= f.label :shift %><br>
    <%= f.select(:shift, ["Morning", "Afternoon", "Evening", "Overnight"],
      {prompt: "-- Select one --"}, {required: true, class: "form-control"}) %>
  </div>
  <div class="form-group" id="select">
    <%= f.label :employment_type, "Employment Type" %><br>
    <%= f.select(:employment_type, ["Transitional", "Supported"],
      {prompt: "-- Select one --"}, {required: true,
      class: "form-control"}) %>
  </div>
  <div class="field form-group">
    <%= f.label :start_date, "Start Date" %><br>
    <%= f.text_field :start_date, class: "datepicker", required: true %>
  </div>
  <div class="field form-group">
    <%= f.label :est_end_date, "Est. End Date" %><br>
    <%= f.text_field :est_end_date, class: "datepicker", required: true %>
  </div>
  <div class="field form-group">
    <%= f.label :te_placement_manager, "Placement Manager" %><br>
    <%= f.text_field :te_placement_manager, class: "form-control", required: true %>
  </div>
  <div class="field form-group">
    <%= f.label :member_working, "Member Working" %><br>
    <%= f.text_field :member_working, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/listings/_listing_options.html.erb
<div id="options">
  <div class="btn-group" id="order-button">
    <button type="button" class="btn btn-primary dropdown-toggle"
     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Order By <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Company", url_for(params.merge({id: params[:id], search:
                    params[:search], order: :company_id, open_jobs: params[:open_jobs],
                    employment_filter: params[:employment_filter]})), method: :get %></li>
      <li><%= link_to "Job Title", url_for(params.merge({id: params[:id], search:
                    params[:search], order: :job_title, open_jobs: params[:open_jobs],
                    order_direction: "asc", employment_filter: params[:employment_filter]})),
        method: :get %></li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search:
                          params[:search], order: :wage, order_direction: "asc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Wage <span class="glyphicon glyphicon-triangle-top"
              aria-hidden="true"></span>
        <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search:
                          params[:search], order: :wage, order_direction: "desc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Wage <span class="glyphicon glyphicon-triangle-bottom"
              aria-hidden="true"></span>
        <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search:
                          params[:search], order: :hours_weekly, order_direction: "asc",
                          open_jobs: params[:open_jobs], employment_filter:
                          params[:employment_filter]})), method: :get do %>
            Hours/week <span class="glyphicon glyphicon-triangle-top"
              aria-hidden="true"></span>
        <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search:
                          params[:search], order: :hours_weekly, order_direction: "desc",
                          open_jobs: params[:open_jobs], employment_filter:
                          params[:employment_filter]})), method: :get do %>
            Hours/week <span class="glyphicon glyphicon-triangle-bottom"
              aria-hidden="true"></span>
        <% end %>
      </li>
      <li><%= link_to "Shift", url_for(params.merge({id: params[:id], search:
                    params[:search], order: :shift, order_direction: "asc", open_jobs:
                    params[:open_jobs], employment_filter: params[:employment_filter]})),
        method: :get %></li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search: params[:search],
                          order: :start_date, order_direction: "asc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Start Date <span class="glyphicon glyphicon-triangle-top"
              aria-hidden="true"></span>
          <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search: params[:search],
                          order: :start_date, order_direction: "desc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Start Date <span class="glyphicon glyphicon-triangle-bottom"
              aria-hidden="true"></span>
          <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search: params[:search],
                          order: :est_end_date, order_direction: "asc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Est. End Date <span class="glyphicon glyphicon-triangle-top"
              aria-hidden="true"></span>
          <% end %>
      </li>
      <li>
        <%= link_to url_for(params.merge({id: params[:id], search: params[:search],
                          order: :est_end_date, order_direction: "desc", open_jobs:
                          params[:open_jobs], employment_filter: params[:employment_filter]})),
          method: :get do %>
            Est. End Date <span class="glyphicon glyphicon-triangle-bottom"
              aria-hidden="true"></span>
          <% end %>
      </li>
    </ul>
  </div>

  <div class="btn-group" id="open_jobs">
    <%= link_to "Open Jobs", url_for(params.merge({id: params[:id], search: params[:search],
              order: params[:order], open_jobs: true,
              employment_filter: params[:employment_filter]})), class: "btn btn-success",
      method: :get %>
  </div>
  <div class="btn-group" id="all_jobs">
    <%= link_to "All Jobs", listings_path(order: params[:order]),
    class: "btn btn-danger", method: :get %>
  </div>
</div>

app/views/listings/_table_header.html.erb
<tr class="info table_row">
  <td><strong>Company</strong></td>
  <td><strong>Job Title</strong></td>
  <td><strong>Description</strong></td>
  <td><strong>Wage</strong></td>
  <td><strong>Schedule</strong></td>
  <td><strong>Hours/week</strong></td>
  <td><strong>Shift</strong></td>
  <% unless params[:employment_filter] %>
    <td><strong>Employment Type</strong></td>
  <% end %>
  <td><strong>Start Date</strong></td>
  <td><strong>Est. End Date</strong></td>
  <td><strong>Placement Manager</strong></td>
  <% if logged_in? %>
    <td><strong>Member Working</strong></td>
    <td><strong>Admin</strong></td>
  <% else %>
    <td><strong>Open?</strong></td>
  <% end %>
</tr>

app/views/listings/_table_row.html.erb
<td><%= link_to found.company.name, company_path(found.company_id) %></td>
<td><%= found.job_title %></td>
<td><%= found.description %></td>
<td><%= zero_wage_handler(found.wage) %></td>
<td><%= found.working_hours_desc %></td>
<td><%= decimalize(found.hours_weekly) %></td>
<td><%= found.shift %></td>
<% unless params[:employment_filter] %>
  <td><%= found.employment_type %></td>
<% end %>
<td><%= found.start_date %></td>
<td><%= found.est_end_date %></td>
<td><%= found.te_placement_manager %></td>
<% if logged_in? %>
  <td><%= found.member_working %></td>
  <td>
    <%= link_to "Show", found %><br>
    <%= link_to "Edit", edit_listing_path(found) %><br>
    <%= link_to "Delete", found, method: :delete, data: { confirm:
      "Are you sure you want to delete?" } %>
  </td>
<% else %>
  <% case found.member_working %>
  <% when "" %>
    <td>Yes</td>
  <% else %>
    <td>No</td>
  <% end %>
<% end %>

app/views/listings/edit.html.erb
<% provide(:title, "Edit Listing") %>

<div class="form_wrapper">
  <h1>Edit Listing</h1>

  <%= link_to "Back", listing_path(listing) %>

  <%= render "form" %>
</div>

app/views/listings/index.html.erb
<% provide(:title, "#{params[:employment_filter]} Listings") %>

<% javascript_include_tag "side_panel" %>

<% if params[:employment_filter] %>
  <%= render "shared/side_panel_opener" %>
<% end %>

<div id="outer_wrapper">
  <% case params[:employment_filter] %>
  <% when "Transitional" %>
    <%= render layout: "shared/side_panel" do %>
      <h1 class="side_panel_heading">Transitional Employment</h1>
      <h5 class="side_panel_desc">
        TE is a part-time job placement managed by Fountain House at outside employer’s places of business. TEs are usually limited to 6 months. You do not generally need a resume, cover letter or interview to secure a placement. Members receive on-the-job training from workers at Fountain House on the job site. The employer pays members the prevailing wage of the position. To obtain a TE please see one of the placement managers connected to the TE.
      </h5>
    <% end %>
  <% when "Supported" %>
    <%= render layout: "shared/side_panel" do %>
      <h1 class="side_panel_heading">Supported Employment</h1>
      <h5 class="side_panel_desc">
        SE is a job placement without time-limits. It is generally part-time work. Often the employer has a relationship with Fountain House. Most SEs require a resume and interview. You can receive help with a resume, cover letter and interview prep from the FH Employment Resource Center.
      </h5>
    <% end %>
  <% end %>

  <%= render partial: "shared/listing_display", locals: {directory: "listings",
    directory_table: "listings"} %>
</div>

<center>
  <%= will_paginate result, renderer: BootstrapPagination::Rails %>
</center>

app/views/listings/new.html.erb
<% provide(:title, "New Listing") %>

<div class="form_wrapper">
  <h1>New Listing</h1>

  <%= render "form" %>
</div>

app/views/listings/show.html.erb
<p><span>Company Name:</span> <%= listing.company.name %></p>
<p><span>Job Title:</span> <%= listing.job_title %></p>
<p><span>Description:</span> <%= listing.description %></p>
<p><span>Wage:</span> <%= decimalize(listing.wage) %></p>
<p><span>Schedule:</span> <%= listing.working_hours_desc %></p>
<p><span>Hours/week:</span> <%= decimalize(listing.hours_weekly) %></p>
<p><span>Shift:</span> <%= listing.shift %></p>
<p><span>Employment Type:</span> <%= listing.employment_type %></p>
<p><span>Start Date:</span> <%= listing.start_date %></p>
<p><span>Est. End Date:</span> <%= listing.est_end_date %></p>
<p><span>Placement Manager:</span> <%= listing.te_placement_manager %></p>
<p><span>Member Working:</span> <%= listing.member_working %></p>
<br>
<%= link_to "<< Back to Listings", listings_path %>
<% if logged_in? %>
  | <%= link_to "Edit", edit_listing_path(listing) %>
  | <%= link_to "Delete", listing, method: :delete, data: { confirm:
    "Are you sure you want to delete?" } %>
<% end %>