config/routes.rb
Rails.application.routes.draw do

  if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" =>
      proc { [200, {}, [ ENV["ACME_KEY"] ] ] }
  else
    ENV.each do |var, _|
      next unless var.start_with?("ACME_TOKEN_")
      number = var.sub(/ACME_TOKEN_/, '')
      get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" =>
        proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
    end
  end
  
  resources :companies do
     collection do
       delete :destroy_all_listings
     end
  end

  resources :companies

  resources :admins
  resources :admin_sessions, only: [:new, :create, :destroy]

  resources :listings do
    get :autocomplete_company_name, :on => :collection
  end

  resources :listings

  resources :external_listings, only: [:new, :create, :index, :edit, :update, :destroy]

  get "login" => "admin_sessions#new"
  get "logout" => "admin_sessions#destroy"

  get "pages/home"
  get "pages/b_1619"
  get "pages/pass"
  get "pages/subsidy"
  get "pages/ticket_to_work"
  get "pages/trial_work_period"
  get "pages/sga"
  get "pages/benefits_calc"
  post "pages/benefits_calc"

  root to: "pages#home"

  get '*path' => redirect('/')
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</p>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/admins/edit.html.erb
<% provide(:title, "Edit Admin") %>

<div class="form_wrapper">
  <h1>Editing Admin</h1>

  <%= link_to 'Show', @admin %> |
  <%= link_to 'Back', admins_path %>

  <%= render 'form' %>
</div>

app/views/admins/index.html.erb
<% provide(:title, "Admin Panel") %>

<p id="notice"><%= notice %></p>

<h3>Administrator List</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>E-mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= link_to "Show", admin %></td>
        <td><%= link_to "Edit", edit_admin_path(admin) %></td>
        <td><%= link_to "Delete", admin, method: :delete, data: { confirm:
          "Are you sure you want to delete?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Admin", new_admin_path %>

app/views/admins/new.html.erb
<% provide(:title, "New Admin") %>

<div class="form_wrapper">
  <h1>New Admin</h1>

  <%= render 'form' %>

  <%= link_to 'Back', admins_path %>
</div>

app/views/admins/show.html.erb
<% provide(:title, "Admin") %>

<p id="notice"><%= notice %></p>

<p>
  <strong>E-mail:</strong>
  <%= @admin.email %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>