config/routes.rb
Rails.application.routes.draw do

  if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" =>
      proc { [200, {}, [ ENV["ACME_KEY"] ] ] }
  else
    ENV.each do |var, _|
      next unless var.start_with?("ACME_TOKEN_")
      number = var.sub(/ACME_TOKEN_/, '')
      get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" =>
        proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
    end
  end
  
  resources :companies do
     collection do
       delete :destroy_all_listings
     end
  end

  resources :companies

  resources :admins
  resources :admin_sessions, only: [:new, :create, :destroy]

  resources :listings do
    get :autocomplete_company_name, :on => :collection
  end

  resources :listings

  resources :external_listings, only: [:new, :create, :index, :edit, :update, :destroy]

  get "login" => "admin_sessions#new"
  get "logout" => "admin_sessions#destroy"

  get "pages/home"
  get "pages/b_1619"
  get "pages/pass"
  get "pages/subsidy"
  get "pages/ticket_to_work"
  get "pages/trial_work_period"
  get "pages/sga"
  get "pages/benefits_calc"
  post "pages/benefits_calc"

  root to: "pages#home"

  get '*path' => redirect('/')
end

app/views/shared/_company_logos_display_block.html.erb
<table>  
  <% result.each do |company| %>
    <%= link_to company_path(company),
      class: "logo_medium btn btn-info " + yield do %>
      <% if company.logo.exists? %>
        <div class="logo_text_with_image">
          <%= image_tag company.logo.url(:thumb) %>
          <h5><%= company.description %></h5>
        </div>
      <% else %>
        <div class="logo_text">
          <h2><%= company.name %></h2>
          <h5><%= company.description %></h5>
        </div>
      <% end %>
    <% end %>
  <% end %>
</table>

app/views/shared/_footer.html.erb
<h5 id="footer" class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <% if logged_in? %>
      <%= link_to "Post New External Listing", new_external_listing_path, class: "footer_link" %>
      <%= link_to "Post New Listing", new_listing_path, class: "footer_link" %>
      <%= link_to "Create New Company", new_company_path, class: "footer_link" %>
      <%= link_to "Administrator Panel", admins_path, class: "footer_link" %>
      <span>
        <%= "Logged in as #{current_user.email}" %>
        <%= link_to "Logout", logout_path %>
      </span>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </div>
</h5>

app/views/shared/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-75475611-1', 'auto');
  </script>
<% end %>

app/views/shared/_google_analytics_pageview.html.erb
<% if Rails.env == "production"  %>
  <script>
    ga('send', 'pageview', '<%= request.path %>');
  </script>
<% end %>

app/views/shared/_listing_display.html.erb
<div id="listings_table" class="table-responsive">
  <%= render "#{directory}/listing_options" %>
  <table class="table">
    <%= render "#{directory_table}/table_header" %>
    <% result.each do |listing| %>
      <% if listing.employment_type == "Supported" %>
        <tr class="table_row supported_emp">
      <% else %>
        <tr class="table_row">
      <% end %>
        <%= render partial: "#{directory_table}/table_row", locals: {found:
          listing} %>
        </tr>
    <% end %>
  </table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar-collapse-area"
        aria-expanded="false">
        <img alt="FH" src="<%= image_path("https://s3.amazonaws.com/fountainhouse-bucket/fh-logo.jpg") %>">
      </button>
      <a class="navbar-brand" id="site_title" href="<%= root_path %>">
        Employment Hub
      </a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-area">
      <ul class="nav navbar-nav navbar-right">
        <%= render "shared/search_bar" %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle"
            data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            Companies <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Companies",
              companies_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Social Enterprises",
              companies_path(social_enterprise: true), method: :get %></li>
          </ul>
        </li>
      
        <li class="dropdown">
          <a href="#" class="dropdown-toggle"
            data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            Social Security Benefits <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Benefits Calculator (SSD-SSI-DUAL)",
              pages_benefits_calc_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "PASS Plan", pages_pass_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Ticket To Work", pages_ticket_to_work_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Trial Work Period", pages_trial_work_period_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Substantial Gainful Activity (SGA)",
              pages_sga_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "1619(b)", pages_b_1619_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Subsidy or Special Condition", pages_subsidy_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle"
            data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            Employment Type <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Types", listings_path(search: params[:search],
              order: params[:order], open_jobs: params[:open_jobs]), method: :get %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Transitional", listings_path(search: params[:search],
              order: params[:order], open_jobs: params[:open_jobs], employment_filter:
              "Transitional"), method: :get %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Supported", listings_path(search: params[:search], order:
              params[:order], open_jobs: params[:open_jobs], employment_filter:
              "Supported"), method: :get %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "External Job Listings", external_listings_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_search_bar.html.erb
<%= form_tag listings_path, id: "search_bar", method: :get,
  class: "navbar-form navbar-left" do %>
  <%= text_field_tag :search, params[:search], autofocus: true,
    placeholder: "Search job listings", size: 50, class: "form-control" %>
  <%= submit_tag "Search", class: "btn btn-default" %>
<% end %>

app/views/shared/_side_panel.html.erb
<div class="fade-panel">
  <%= yield %>
</div>

app/views/shared/_side_panel_opener.html.erb
<div class="opener">
  <button href= "#" class="btn btn-danger">
    <i id="chevron" class="glyphicon glyphicon glyphicon-chevron-left"></i>
  </button>
</div>