config/routes.rb
Rails.application.routes.draw do

  if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" =>
      proc { [200, {}, [ ENV["ACME_KEY"] ] ] }
  else
    ENV.each do |var, _|
      next unless var.start_with?("ACME_TOKEN_")
      number = var.sub(/ACME_TOKEN_/, '')
      get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" =>
        proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
    end
  end
  
  resources :companies do
     collection do
       delete :destroy_all_listings
     end
  end

  resources :companies

  resources :admins
  resources :admin_sessions, only: [:new, :create, :destroy]

  resources :listings do
    get :autocomplete_company_name, :on => :collection
  end

  resources :listings

  resources :external_listings, only: [:new, :create, :index, :edit, :update, :destroy]

  get "login" => "admin_sessions#new"
  get "logout" => "admin_sessions#destroy"

  get "pages/home"
  get "pages/b_1619"
  get "pages/pass"
  get "pages/subsidy"
  get "pages/ticket_to_work"
  get "pages/trial_work_period"
  get "pages/sga"
  get "pages/benefits_calc"
  post "pages/benefits_calc"

  root to: "pages#home"

  get '*path' => redirect('/')
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :listings, inverse_of: :company
  has_attached_file :logo, styles: { medium: "200x200>", thumb: "100x100>" },
    s3_protocol: :https
  validates_attachment_content_type :logo,
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  include PgSearch
  pg_search_scope :search_companies, against: [:name, :description],
                  using: { tsearch: { dictionary: "english" } }

  def self.search(search)
    results = Company.search_companies(search)
    return Listing.search_listings("") if results.empty?
    results_array = []
    results.each do |result|
      results_array << Listing.search_listing_by_company(result[:id])
    end
    if results_array.count > 1
      counter = 1
      final = results_array[0].dup
      until counter == results_array.count
        final = final.union(results_array[counter])
        counter += 1
      end
      return final
    else
      return results_array[0]
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  attr_accessor :result, :company
  helper_method :result, :company

  def index
    if params[:social_enterprise]
      @result = Company.where("social_enterprise = ?", true)
    else
      @result = Company.all
    end
    @result = orderer(@result, "name")
    @result = paginated(@result, 24)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.save
    if @company.valid?
      @company.save
      redirect_to(company_path(@company), notice:
        "Company created successfully")
    else
      flash[:error] = @company.errors.full_messages.to_sentence
      redirect_to(new_company_path)
    end
  end

  def edit
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice:
        "Company was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def destroy_all_listings
    company_id = params[:id]
    company = Company.find(company_id)
    Listing.where("company_id = ?", company_id).each do |listing|
      listing.destroy
    end
    redirect_to(company_path(company), notice: "All listings for" +
      " #{company.name} deleted.")
  end

  rescue_from "ActiveRecord::InvalidForeignKey" do
    message = "Before deleting a company, you must delete all of its job" +
    " listings. To do that, you can click on \"Delete all listings.\""
    flash[:error] = message
    redirect_to(company_path(@company))
  end

  def show
    @result = Listing.where("company_id = ?", @company.id)
    @result = show_open_jobs(@result) if params[:open_jobs]
    @result = orderer(@result, params[:order], params[:order_direction]) if
      params[:order]
    @result = paginated(@result)
  end

  def update
    if @company.valid?
      @company.update(company_params)
      redirect_to(company_path(@company), notice: "Company edited successfully")
    else
      flash[:error] = @company.errors.full_messages.to_sentence
      redirect_to(edit_company_path(@company))
    end
  end

  private

    def company_params
      params.require(:company).permit(:name, :description, :social_enterprise,
        :logo)
    end

    def set_company
      @company = Company.find(params[:id])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company_form.html.erb
<%= form_for(company, html: {multipart: true}) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</p>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, "Company Name" %><br>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field form-group">
    <%= f.label :description, "Company Description" %><br>
    <%= f.text_area :description, rows: 5, cols: 40 %>
  </div>

  <div class="field form-group">
    <%= f.label "Social Enterprise" %> &nbsp;&nbsp;
    <%= f.check_box :social_enterprise %>
  </div>

  <% if company.logo.exists? %>
    <%= image_tag company.logo.url %><br>
  <% end %>
  <div class="field form-group">
    <%= f.label :logo, "Add a company logo image" %><br>
    <%= f.file_field :logo %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/companies/_table_header.html.erb
<tr class="info table_row">
  <td><strong>Job Title</strong></td>
  <td><strong>Description</strong></td>
  <td><strong>Wage</strong></td>
  <td><strong>Schedule</strong></td>
  <td><strong>Hours/week</strong></td>
  <td><strong>Shift</strong></td>
  <td><strong>Employment Type</strong></td>
  <td><strong>Start Date</strong></td>
  <td><strong>Est. End Date</strong></td>
  <td><strong>Placement Manager</strong></td>
  <% if logged_in? %>
    <td><strong>Member Working</strong></td>
    <td><strong>Admin</strong></td>
  <% else %>
    <td><strong>Open?</strong></td>
  <% end %>
</tr>

app/views/companies/_table_row.html.erb
<td><%= found.job_title %></td>
<td><%= found.description %></td>
<td><%= zero_wage_handler(found.wage) %></td>
<td><%= found.working_hours_desc %></td>
<td><%= decimalize(found.hours_weekly) %></td>
<td><%= found.shift %></td>
<td><%= found.employment_type %></td>
<td><%= found.start_date %></td>
<td><%= found.est_end_date %></td>
<td><%= found.te_placement_manager %></td>
<% if logged_in? %>
  <td><%= found.member_working %></td>
  <td>
    <%= link_to "Show", found %><br>
    <%= link_to "Edit", edit_listing_path(found) %><br>
    <%= link_to "Delete", found, method: :delete, data: { confirm:
      "Are you sure you want to delete?" } %>
  </td>
<% else %>
  <% case found.member_working %>
  <% when "" %>
    <td>Yes</td>
  <% else %>
    <td>No</td>
  <% end %>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Edit Company") %>

<div class="form_wrapper">
  <%= link_to "Back", company_path(company) %>

  <%= render "company_form" %>
</div>

app/views/companies/index.html.erb
<% provide(:title, "Companies") %>

<% javascript_include_tag "side_panel" %>

<%= render "shared/side_panel_opener" %>

<div id="outer_wrapper">
  <% case params[:social_enterprise] %>
  <% when "true" %>
    <%= render layout: "shared/side_panel" do %>
      <h1 class="side_panel_heading">Social Enterprises</h1>
      <h5 class="side_panel_desc">
        Fountain House recently launched a social enterprise and social
        cooperative program designed to create alternative employment
        opportunities and encourage entrepreneurship among members.
        <br><br>
        Social enterprise achieves a double bottom-line. It offers affordable,
        top-quality services to clients while providing employees from
        traditionally marginalized populations with the opportunity to enter the
        workforce and obtain invaluable job skills.  Through innovative and
        entrepreneurial ventures, members learn industry specific skills that are
        transferable in the marketplace.
      </h5>
    <% end %>
  <% else %>
    <%= render layout: "shared/side_panel" do %>
      <h1 class="side_panel_heading">All Companies</h1>
    <% end %>
  <% end %>

  <div id="company_box_display">
    <%= render partial: "shared/company_logos_display_block", locals: {result:
      result} %>
  </div>
</div>

<div class="paginator">
  <%= will_paginate result, renderer: BootstrapPagination::Rails %>
</div>

app/views/companies/new.html.erb
<% provide(:title, "New Company") %>

<div class="form_wrapper">
  <%= render "company_form" %>
</div>

app/views/companies/show.html.erb
<% provide(:title, company.name) %>

<% javascript_include_tag "side_panel" %>

<%= render "shared/side_panel_opener" %>

<div id="outer_wrapper">
  <%= render layout: "shared/side_panel" do %>
    <center>
      <div class="logo_medium btn btn-info">
        <% if company.logo.exists? %>
          <div class="logo_text_with_image">
            <%= image_tag company.logo.url(:thumb) %>
            <h5><%= company.description %></h5>
          </div>
        <% else %>
          <div class="logo_text">
            <h2><%= company.name %></h2>
          </div>
        <% end %>
      </div>
    </center>
    <p class="side_panel_desc">
      <%= company.description %>
    </p>
  <% end %>

  <%= render partial: "shared/listing_display", locals: {directory: "listings",
    directory_table: "companies"} %>
</div>

<center>
  <%= will_paginate result, renderer: BootstrapPagination::Rails %>
</center>

<br>
<% if logged_in? %>
  <%= link_to "Edit", edit_company_path(company) %>
  | <%= link_to "Delete", company, method: :delete, data: { confirm:
  "Are you sure you want to delete?" } %>
  | <%= link_to "Delete All Listings", destroy_all_listings_companies_path(id: company.id), method: :delete, data: { confirm: "Are you sure you want to delete all listings for this company?" } %>
<% end %>